# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0014_auto_20170705_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_fetched_groups',
            field=models.DateTimeField(blank=True, default=None, help_text='If older than 5 min, groups will be fetched from Azure next time the user makes a request.', null=True),
        ),
    ]
