# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20170221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifvalue',
            name='verif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifValues', to='board.Verif'),
        ),
    ]
