# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20170221_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
