# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_verif_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='exceptions',
            field=models.ManyToManyField(related_name='exception', to='board.Computer'),
        ),
    ]
