# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20170227_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verif',
            name='tag',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
