# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20170227_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='verif',
            name='exceptions',
        ),
        migrations.AddField(
            model_name='exceptionrules',
            name='verif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifExceptions', to='board.Verif'),
        ),
    ]
