# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20170227_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionrule',
            name='verif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptionRules', to='board.Verif'),
        ),
    ]
