# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20170227_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionrule',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
