# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_exceptionrule_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='count_since_mail',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
