# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_computer_count_since_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='not_ok_since',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
