# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20170520_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='count_since_mail',
        ),
        migrations.AddField(
            model_name='computer',
            name='error_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
