# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20170522_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='verif',
            name='icon_type',
            field=models.CharField(choices=[('s', 'Solid (fas)'), ('r', 'Regular (far)'), ('b', 'Brand (fab)')], default='s', max_length=2),
        ),
    ]
